# tomcat配置
server:
  port: 19090

# spring配置
spring:
  profiles:
    active: dev
  datasource:
    username: ${mysql.username}
    password: ${mysql.password}
    url: jdbc:mysql://${mysql.host}/${mysql.database}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    port: ${redis.port}
    host: ${redis.host}
  thymeleaf:
    cache: true
shiro-redis:
  enabled: true
  redis-manager:
    host: ${redis.host}
    port: ${redis.port}

# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为0)
      id-type: auto # 主键策略：自增
  type-aliases-package: com.project.blog.pojo.po # po实体包

jwt:
  # 加密秘钥
  secret: vue-blog
  # token有效时长，7天，单位秒
  expire: 604800
  header: token
