# mysql配置
mysql:
  host: localhost:13307
  database: blog
  username: root
  password: 123456

# minio配置
minio:
  access-key: minioadmin
  secret-key: minioadmin
  end-point: http://127.0.0.1:19000
  bucket-name: vueblog-img
  domain: http://127.0.0.1:19000/vueblog-img/

# 安全配置
security:
  # JWT配置
  jwt:
    access-token:
      # 加密秘钥
      secret: vue-blog-access
      # 访问token有效时长，1天，单位秒
      expire: 86400
    refresh-token:
      # 加密秘钥
      secret: vue-blog-refresh
      # 刷新token有效时长，30天，单位秒
      expire: 2592000

  # 白名单配置
  white-ignore:
    ignores:
      - uri: /article
        methods:
          - GET
      - uri: /article/new
        methods:
          - GET
      - uri: /article/id/**
        methods:
          - GET
      - uri: /article/detail/**
        methods:
          - GET
      - uri: /article/author/info/**
        methods:
          - GET
      - uri: /user/login
        methods:
          - POST
      - uri: /user/register
        methods:
          - POST
