# tomcat配置
server:
  port: 19090

# spring配置
spring:
  profiles:
    active: dev
  datasource:
    username: ${mysql.username}
    password: ${mysql.password}
    url: jdbc:mysql://${mysql.host}/${mysql.database}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    # 文件上传配置
    multipart:
      max-file-size: 10MB # 最大上传大小

# shiro-redis配置
shiro-redis:
  enabled: true
  redis-manager:
    host: ${redis.host}
    port: ${redis.port}

# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为0)
      id-type: auto # 主键策略：自增
  type-aliases-package: com.project.blog.pojo.po # po实体包

# XFileStorage配置
dromara:
  x-file-storage: #文件存储配置
    default-platform: minio-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    #对应平台的配置写在这里，注意缩进要对齐
    minio:
      - platform: minio # 自定义存储平台标识
        enable-storage: true  # 启用存储
        access-key: ${minio.access-key}
        secret-key: ${minio.secret-key}
        end-point: ${minio.end-point}
        bucket-name: ${minio.bucket-name}
        domain: ${minio.domain} # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path: "" # 上传文件公共前缀基路径

# JWT配置
jwt:
  # 加密秘钥
  secret: vue-blog
  # token有效时长，7天，单位秒
  expire: 604800
  header: token
